### ISSUE TITLE
ProductRelationship.type alignment

### ISSUE THREAD

**Issue by softdevadamlach** [MEF-GIT/MEF-LSO-Sonata-SDK#137] opened 2020-01-22 11:41 UTC
What:
ProductRelationship.type are defined in a different way in Poq/Quote/Order management api definition.

Where:
Quote/Order Management api definition.

Details:

POQ:
it is an enum:
https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/ad464b58c470ba7e23da37a98e4f54debb04e0e9/api/Serviceability/MEF_api_productOfferingQualificationManagement_3.0.1.yaml#L626

Quote
it is a string (description indicates the same values as in enum):
https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/ad464b58c470ba7e23da37a98e4f54debb04e0e9/api/Quote/MEF_api_quoteManagement_2.0.0.yaml#L981

Order:
same situation like in Quote.

I suggest to introduce Enum to Quote and Order api.

**Comment by bigludo7** [comment] 2020-01-27 15:32
Look like it is contradictory with https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/issues/133 
Need a common decision

**Comment by softdevadamlach** [comment] 2020-01-28 11:32
The only suggested solution is contradictory. The main goal to align between is not.
After deeper analysis, I agree with @bartoszm so I suggest aligning everywhere to String.

**Comment by bigludo7** [comment] 2020-03-10 08:55
Duplicate of #133 (merge both)

**Closed by bigludo7** 2020-03-10 08:55 UTC
